version: '3'

services:

  base: &base
    restart: unless-stopped
    image: chatwoot/chatwoot:develop
    env_file: .env ## Change this file for customized env variables
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./data/storage:/app/storage    

  rails:
    <<: *base
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production   
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production     
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:12-bullseye
    restart: unless-stopped
    expose:
      - '5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chatwoot

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env ## Change this file for customized env variables
    volumes:
      - ./data/redis:/data
    expose:
      - '6379'
